workflows:
  expo-android-workflow:
    name: Expo Android Build (Native)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_PUBLIC_EXPO_PUSH_API_URL: $EXPO_PUBLIC_EXPO_PUSH_API_URL
        EXPO_PUBLIC_S3_STORAGE_URL: $EXPO_PUBLIC_S3_STORAGE_URL
        EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB: $EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB
      node: 20.18.0
      npm: 10.8.2
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Generate native Android project
        script: |
          npx expo prebuild --platform android --clean
      - name: Fix Kotlin version
        script: |
          sed -i '' "s/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24')/g" android/build.gradle || sed -i "s/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24')/g" android/build.gradle
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace --info
      - name: Build Android AAB (optional)
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - alpsungurk@hotmail.com
        notify:
          success: true
          failure: false

  expo-ios-workflow:
    name: Expo iOS Build (Native)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_PUBLIC_EXPO_PUSH_API_URL: $EXPO_PUBLIC_EXPO_PUSH_API_URL
        EXPO_PUBLIC_S3_STORAGE_URL: $EXPO_PUBLIC_S3_STORAGE_URL
        EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB: $EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB
        APP_STORE_ID: $APP_STORE_ID
        APPLE_ID: $APPLE_ID
        APPLE_APP_SPECIFIC_PASSWORD: $APPLE_APP_SPECIFIC_PASSWORD
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      node: 20.18.0
      npm: 10.8.2
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Generate native iOS project
        script: |
          npx expo prebuild --platform ios --clean
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace ios/*.xcworkspace \
            -scheme $(xcode-project detect-scheme) \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/ios/$(xcode-project detect-scheme).xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export iOS IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/$(xcode-project detect-scheme).xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - alpsungurk@hotmail.com
        notify:
          success: true
          failure: false

