workflows:
  expo-android-workflow:
    name: Expo Android Build (Native)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_PUBLIC_EXPO_PUSH_API_URL: $EXPO_PUBLIC_EXPO_PUSH_API_URL
        EXPO_PUBLIC_S3_STORAGE_URL: $EXPO_PUBLIC_S3_STORAGE_URL
        EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB: $EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB
      node: 20.18.0
      npm: 10.8.2
    scripts:
      - name: Install dependencies
        script: |
          npm install
          # Verify React Native gradle plugin is installed
          node -e "require.resolve('@react-native/gradle-plugin/package.json', { paths: [require.resolve('react-native/package.json')] })" || echo "Warning: @react-native/gradle-plugin not found"
      - name: Generate JavaScript bundle
        script: |
          npx expo export:embed --platform android
      - name: Generate native Android project
        script: |
          npx expo prebuild --platform android --clean
      - name: Fix Kotlin version and package name
        script: |
          # Fix Kotlin version
          sed -i '' "s/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24')/g" android/build.gradle || sed -i "s/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')/classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24')/g" android/build.gradle
          # Fix package name in Kotlin files (if needed)
          # Package name is now com.ilkcoffee.app, no conversion needed
          # Disable minification for debugging (geçici olarak)
          sed -i '' 's/minifyEnabled enableMinifyInReleaseBuilds/minifyEnabled false/g' android/app/build.gradle || sed -i 's/minifyEnabled enableMinifyInReleaseBuilds/minifyEnabled false/g' android/app/build.gradle
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace
      - name: Build Android AAB (optional)
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - alpsungurk@hotmail.com
        notify:
          success: true
          failure: false

