workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_credentials # Codemagic UI'da oluşturmanız gerekecek
      vars:
        # Environment variables - app.config.js'de kullanılan değişkenler
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_PUBLIC_EXPO_PUSH_API_URL: $EXPO_PUBLIC_EXPO_PUSH_API_URL
        EXPO_PUBLIC_S3_STORAGE_URL: $EXPO_PUBLIC_S3_STORAGE_URL
        EXPO_PUBLIC_GOOGLE_CLIENT_ID: $EXPO_PUBLIC_GOOGLE_CLIENT_ID
        
        # Android Signing - Production keystore için
        # Keystore dosyasını base64 encode edip buraya ekleyin
        CM_KEYSTORE_PATH: $CM_KEYSTORE_PATH
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_ALIAS: $CM_KEY_ALIAS
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD
      node: 20.11.0
      npm: 10.2.4
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Prebuild Android (if needed)
        script: |
          npx expo prebuild --platform android --clean
      
      - name: Setup Android keystore
        script: |
          # Production keystore'u environment variable'dan al
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 --decode > android/app/release.keystore
            # gradle.properties'e signing bilgilerini ekle
            echo "MYAPP_RELEASE_STORE_FILE=release.keystore" >> android/gradle.properties
            echo "MYAPP_RELEASE_STORE_PASSWORD=$CM_KEYSTORE_PASSWORD" >> android/gradle.properties
            echo "MYAPP_RELEASE_KEY_ALIAS=$CM_KEY_ALIAS" >> android/gradle.properties
            echo "MYAPP_RELEASE_KEY_PASSWORD=$CM_KEY_PASSWORD" >> android/gradle.properties
          else
            echo "⚠️ Production keystore bulunamadı, debug keystore kullanılacak"
          fi
      
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
      
      - name: Build Android AAB (App Bundle)
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com # Kendi email adresinizle değiştirin
        notify:
          success: true
          failure: true
      scripts:
        - name: Upload to Codemagic
          script: |
            echo "Build başarıyla tamamlandı!"
            echo "APK ve AAB dosyaları artifacts bölümünde mevcut."

  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_PUBLIC_EXPO_PUSH_API_URL: $EXPO_PUBLIC_EXPO_PUSH_API_URL
        EXPO_PUBLIC_S3_STORAGE_URL: $EXPO_PUBLIC_S3_STORAGE_URL
        EXPO_PUBLIC_GOOGLE_CLIENT_ID: $EXPO_PUBLIC_GOOGLE_CLIENT_ID
      node: 20.11.0
      npm: 10.2.4
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --clean
      
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

